

// eslint-disable-next-line no-unused-vars
const dataAttributes = [
    'matricula',
    'nome',
    'sexo',
    'posto',
    'graduacao',
    'antiguidade',
    'lotacao',
    'dataDeIngresso',
    'tempoAnterior',
    'dataDeNascimento',
    'licencasEspeciaisAcumuladas',
    'comportamento',
    'formacao',
    'cursosDeFormacao',
    'cursosPm',
    'cursosCivis',
    'idioma',
    'endereco',
    'ferias',
    'afastamento',
    'restricao',
];

const values = [
    {
        matricula: 900001,
        nome: 'Joaquim Alves da Silva Xavier',
        sexo: 'M',
        postoOuGraduacao: 'Soldado',
        antiguidade: 78, // ?
        lotacao: { regiao: 1, batalhao: 1, companhia: 1, pelotao: 1, grupo: 1, cidade: 'Urussanga' },
        dataDeIngresso: '01/01/2010',
        tempoAnterior: { privado: 720, publicoSc: 0, publicoOutros: 0 },
        dataDeNascimento: '03/01/1980',
        licencasEspeciaisAcumuladas: 6,
        comportamento: 'Excepcional',
        formacao: 'Medicina',
        cursosDeFormacao: ['CFSD', 'CHC'],
        cursosPm: ['Táticas Policiais'],
        cursosCivis: 'Libras',
        idioma: ['Inglês', 'Espanhol', 'Alemão'],
        endereco: 'Avenida Engenheiro Mesquita, 586, Centro, Araranguá/SC',
        ferias: '01/01/2022', // ?
        afastamento: { tipo: 'LTS', inicio: '10/10/2022', fim: '09/11/2022' },
        restricao: [{ tipo: 'Atividade fisica', fim: '12/12/2022' }],
    },
    {
        matricula: 900002,
        nome: 'Douglas Machado',
        sexo: 'M',
        postoOuGraduacao: 'Soldado',
        antiguidade: 78, // ?
        lotacao: { regiao: 1, batalhao: 1, companhia: 1, pelotao: 1, grupo: 1, cidade: 'Araranguá' },
        dataDeIngresso: '01/01/2012',
        tempoAnterior: { privado: 720, publicoSc: 500, publicoOutros: 0 },
        dataDeNascimento: '03/11/1980',
        licencasEspeciaisAcumuladas: 4,
        comportamento: 'Excepcional',
        formacao: 'Direito',
        cursosDeFormacao: ['CFSD', 'CHC'],
        cursosPm: ['Táticas Policiais'],
        cursosCivis: 'Libras',
        idioma: ['Inglês', 'Espanhol'],
        endereco: 'Avenida Engenheiro Mesquita, 586, Centro, Araranguá/SC',
        ferias: '01/01/2022', // ?
        afastamento: { tipo: 'férias', inicio: '10/10/2022', fim: '09/11/2023' },
        restricao: [{ tipo: 'Atividade fisica', fim: '12/12/2022' }],
    },
    {
        matricula: 900003,
        nome: 'Jean Moura',
        sexo: 'M',
        postoOuGraduacao: 'Soldado',
        antiguidade: 78, // ?
        lotacao: { regiao: 1, batalhao: 1, companhia: 1, pelotao: 1, grupo: 1, cidade: 'Araranguá' },
        dataDeIngresso: '01/01/2014',
        tempoAnterior: { privado: 720, publicoSc: 0, publicoOutros: 0 },
        dataDeNascimento: '03/11/1980',
        licencasEspeciaisAcumuladas: 2,
        comportamento: 'Excepcional',
        formacao: 'Direito',
        cursosDeFormacao: ['CFSD', 'CHC'],
        cursosPm: ['Táticas Policiais'],
        cursosCivis: 'Libras',
        idioma: ['Inglês'],
        endereco: 'Avenida Engenheiro Mesquita, 586, Centro, Araranguá/SC',
        ferias: '01/01/2022', // ?
        afastamento: { tipo: 'férias', inicio: '01/01/2022', fim: '12/10/2022' },
        restricao: [{ tipo: 'Atividade fisica', fim: '12/12/2022' }],
    },
    {
        matricula: 900004,
        nome: 'Karine Fernandes',
        sexo: 'F',
        postoOuGraduacao: 'Soldado',
        antiguidade: 78, // ?
        lotacao: { regiao: 1, batalhao: 1, companhia: 1, pelotao: 1, grupo: 1, cidade: 'Araranguá' },
        dataDeIngresso: '01/01/2010',
        tempoAnterior: { privado: 720, publicoSc: 0, publicoOutros: 0 },
        dataDeNascimento: '03/11/1980',
        licencasEspeciaisAcumuladas: 2,
        comportamento: 'Excepcional',
        formacao: 'Direito',
        cursosDeFormacao: ['CFSD', 'CHC'],
        cursosPm: ['Táticas Policiais'],
        cursosCivis: 'Libras',
        idioma: ['Inglês'],
        endereco: 'Avenida Engenheiro Mesquita, 586, Centro, Araranguá/SC',
        ferias: '01/01/2022', // ?
        afastamento: { tipo: 'férias', inicio: '10/10/2022', fim: '10/11/2022' },
        restricao: [{ tipo: 'Atividade fisica', fim: '12/12/2022' }],
    },
    {
        matricula: 1321321,
        nome: 'Messi',
        sexo: 'M',
        postoOuGraduacao: 'Soldado',
        antiguidade: 78, // ?
        lotacao: { regiao: 1, batalhao: 1, companhia: 1, pelotao: 1, grupo: 1, cidade: 'Criciuma' },
        dataDeIngresso: '01/01/1988',
        tempoAnterior: { privado: 0, publicoSc: 0, publicoOutros: 0 },
        dataDeNascimento: '03/01/1980',
        licencasEspeciaisAcumuladas: 4,
        comportamento: 'Excepcional',
        formacao: 'Direito',
        cursosDeFormacao: ['CFSD', 'CHC'],
        cursosPm: ['Táticas Policiais'],
        cursosCivis: 'Libras',
        idioma: ['Inglês'],
        endereco: 'Avenida Engenheiro Mesquita, 586, Centro, Araranguá/SC',
        ferias: '01/01/2022', // ?
        afastamento: { tipo: 'LTS', inicio: '04/10/2022', fim: '09/10/2022' },
        restricao: [{ tipo: 'Atividade fisica', fim: '12/12/2022' }],
    },
    {
        matricula: 945831,
        nome: 'Neymar',
        sexo: 'M',
        postoOuGraduacao: 'Soldado',
        antiguidade: 78, // ?
        lotacao: { regiao: 1, batalhao: 1, companhia: 1, pelotao: 1, grupo: 1, cidade: 'Criciuma' },
        dataDeIngresso: '01/01/1990',
        tempoAnterior: { privado: 720, publicoSc: 0, publicoOutros: 0 },
        dataDeNascimento: '03/01/1980',
        licencasEspeciaisAcumuladas: 6,
        comportamento: 'Excepcional',
        formacao: 'Direito',
        cursosDeFormacao: ['CFSD', 'CHC'],
        cursosPm: ['Táticas Policiais'],
        cursosCivis: 'Libras',
        idioma: ['Inglês'],
        endereco: 'Avenida Engenheiro Mesquita, 586, Centro, Araranguá/SC',
        ferias: '01/01/2022', // ?
        afastamento: { tipo: 'LTS', inicio: '01/01/2022', fim: '12/12/2022' },
        restricao: [{ tipo: 'Atividade fisica', fim: '12/12/2022' }],
    },
    {
        matricula: 900005,
        nome: 'Galvão Bueno',
        sexo: 'M',
        postoOuGraduacao: 'Soldado',
        antiguidade: 78, // ?
        lotacao: { regiao: 1, batalhao: 1, companhia: 1, pelotao: 1, grupo: 1, cidade: 'Araranguá' },
        dataDeIngresso: '01/01/1990',
        tempoAnterior: { privado: 720, publicoSc: 0, publicoOutros: 0 },
        dataDeNascimento: '03/01/1980',
        licencasEspeciaisAcumuladas: 6,
        comportamento: 'Excepcional',
        formacao: 'Direito',
        cursosDeFormacao: ['CFSD', 'CHC'],
        cursosPm: ['Táticas Policiais'],
        cursosCivis: 'Libras',
        idioma: ['Inglês'],
        endereco: 'Avenida Engenheiro Mesquita, 586, Centro, Araranguá/SC',
        ferias: '01/01/2022', // ?
        afastamento: { tipo: 'LTS', inicio: '01/01/2022', fim: '12/12/2022' },
        restricao: [{ tipo: 'Atividade fisica', fim: '12/12/2022' }],
    },      
];

export default values;

